import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:movie/constants.dart';
import 'package:movie/data/models/test.dart';
import 'package:movie/data/repository/repo_controller.dart';

class TestRepo with ChangeNotifier {
  // Dio dio = Dio();
  Autogenerated? autogenerated;
  int pageNumber = 1;
  int? totalPages;
  List<Results> result = [];
  List total = [];
  Future getMostPopularTest({bool isRefresh = false, refreshController}) async {
    await DioHelper.dio.get("movie/popular", queryParameters: {
      // "api_key": apiKey,
      "page": pageNumber.toString()
    }).then((value) {
      autogenerated = Autogenerated.fromJson(value.data);
      totalPages = autogenerated!.totalPages;

      if (isRefresh) {
        pageNumber = 1;
      } else {
        if (pageNumber >= totalPages!) {
          refreshController.loadNoData();
          return false;
        }
      }
      if (isRefresh) {
        result = autogenerated!.results!;
      } else {
        result.addAll(autogenerated!.results!);
      }
      pageNumber++;

      notifyListeners();
    }).catchError((e) {
      print(e);
    });
  }
}
