import 'package:movie/constants.dart';
import 'package:movie/data/models/coming_soon2_model.dart';

class ComingSoonRepo {
  ComingSoonRepo();

  Future<List<ComingResults>> getUpComing(
      {dio, ComingSoon2Model? autogenerated, result}) async {
    await dio
        .get(
      "movie/upcoming",
    )
        .then((value) {
      autogenerated = ComingSoon2Model.fromJson(value.data);
      result = autogenerated!.results;
      // print(autogenerated!.results![0]);
      return result;
    }).catchError((e) {
      print(e);
    });

    return result!;
  }
}
