import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:movie/constants.dart';
import 'package:movie/data/models/test.dart';

class MostPopularRepo {
  MostPopularRepo();

  Future<Autogenerated> getMostPopular({dio, autogenerated}) async {
    await dio.get(baseUrl + "movie/popular",
        queryParameters: {"api_key": apiKey}).then((value) {
      autogenerated = Autogenerated.fromJson(value.data);

      return autogenerated;
    }).catchError((e) {
      print(e);
    });

    return autogenerated!;
  }
}
