import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';

// part of 'test.dart g';
part 'test.g.dart';

@HiveType(typeId: 0)
class Autogenerated {
  @HiveField(0)
  dynamic page;
  @HiveField(1)
  List<Results>? results = [];
  @HiveField(2)
  dynamic totalResults;
  @HiveField(3)
  dynamic totalPages;

  // Autogenerated({this.page, this.results, this.totalResults, this.totalPages});
  Autogenerated();

  Autogenerated.fromJson(Map<String, dynamic> json) {
    page = json['page'];
    if (json['results'] != null) {
      results = <Results>[];
      json['results'].forEach((v) {
        results!.add(Results.fromJson(v));
      });
    }
    totalResults = json['total_results'];
    totalPages = json['total_pages'];
  }
}

@HiveType(typeId: 1)
class Results {
  @HiveField(0)
  String? posterPath;
  @HiveField(1)
  bool? adult;
  @HiveField(2)
  String? overview;
  @HiveField(3)
  String? releaseDate;
  @HiveField(4)
  List<int>? genreIds;
  @HiveField(5)
  dynamic id;
  @HiveField(6)
  String? originalTitle;
  @HiveField(7)
  String? originalLanguage;
  @HiveField(8)
  String? title;
  @HiveField(9)
  String? backdropPath;
  @HiveField(10)
  dynamic popularity;
  @HiveField(11)
  dynamic voteCount;
  @HiveField(12)
  bool? video;
  @HiveField(13)
  dynamic voteAverage;

  Results(
      {this.posterPath,
      this.adult,
      this.overview,
      this.releaseDate,
      this.genreIds,
      this.id,
      this.originalTitle,
      this.originalLanguage,
      this.title,
      this.backdropPath,
      this.popularity,
      this.voteCount,
      this.video,
      this.voteAverage});

  Results.fromJson(Map<String, dynamic> json) {
    posterPath = json['poster_path'];
    adult = json['adult'];
    overview = json['overview'];
    releaseDate = json['release_date'];
    genreIds = json['genre_ids'].cast<int>();
    id = json['id'];
    originalTitle = json['original_title'];
    originalLanguage = json['original_language'];
    title = json['title'];
    backdropPath = json['backdrop_path'];
    popularity = json['popularity'];
    voteCount = json['vote_count'];
    video = json['video'];
    voteAverage = json['vote_average'];
  }
}
