import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:movie/data/models/test.dart';
import 'package:movie/data/repository/movie_repo/most_popular_repo.dart';
import 'package:movie/data/repository/repo_controller.dart';
import 'package:movie/main.dart';

class MostPopularProvider with ChangeNotifier {
  Autogenerated? autogenerated;
  List<Results>? result = [];

  List? tList = [];
  MostPopularProvider() {
    displayMostPopular();
  }
  //

  MostPopularRepo repo = MostPopularRepo();
  displayMostPopular() async {
    // getMore();

    autogenerated = await repo.getMostPopular(
        dio: DioHelper.dio, autogenerated: autogenerated, result: result);
    notifyListeners();
  }
}
